[package]
name = "bom"
version = "0.1.0"
authors = ["Hell HBBD <paulyu602@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["router"] }
rust_decimal = "1"
thiserror = "2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = "0.4"
directories = "6"
rusqlite = { version = "0.32", features = ["backup", "bundled"] }
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
tempfile = "3"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
