[application]
name = "BOM"

[bundle]
identifier = "local.hellhbbd.bom"
publisher = "HellHBBD"
resources = ["assets/data.sqlite"]

[bundle.windows]
icon_path = "assets/icon.ico"
webview_install_mode = { DownloadBootstrapper = { silent = true } }

[bundle.windows.nsis]
installer_icon = "assets/icon.ico"

[web.app]

# HTML title tag content
title = "bom"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
